[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RSFQ_Router"
authors = [{name = "ZiyuLiu", email = "zliu4130@usc.edu"}]
dynamic = ["version", "description"]
